[package]
name = "bevy_mod_raycast"
version = "0.2.2"
authors = ["Aevyrie <aevyrie@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Ray Casting for the Bevy Engine."
repository = "https://github.com/aevyrie/bevy_mod_raycast/"
keywords = ["gamedev", "graphics", "bevy", "3d", "raycast"]
categories = ["game-engines", "rendering"]

[dependencies]
bevy = { version = "0.5", default-features = false, features = ["render"] }

[features]
ex = ["bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/bevy_gltf", "bevy/x11"]

[[example]]
name = "mouse_picking"
required-features = ["ex"]

[[example]]
name = "minimal"
required-features = ["ex"]
